name: Auto Assign and Reviewers
on:
  pull_request:
    types: [opened, ready_for_review, edited, synchronize, reopened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: 'Auto-assign PR'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: hezronkimutai
          numOfAssignee: 2
          allowSelfAssign: true